name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Download dependencies
      run: go mod vendor

    - name: Install packr
      run: go get -u github.com/gobuffalo/packr/packr

    - name: Execute script
      run: ./release.sh 

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: release/*
